# Generated by Django 2.2.10 on 2020-02-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_add_addd"),
    ]

    operations = [
        migrations.RemoveField(model_name="add", name="add",),
        migrations.AddField(
            model_name="add",
            name="dd",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
